# This is a basic workflow that is manually triggered

name: Deploy code on push

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: 
  push:
    branches:
      - main

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: jumpgram

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Pull code from remote
      run: cd /var/www/jumpgram.co/ && git pull
    - name: Fix files permissions
      run: chown -R www-data:www-data /var/www/jumpgram.co
